-- Consulta 1: obter todos os livros favoritos de um usuário específico

SELECT LIVRO.ISBN, LIVRO.TITULO, LIVRO.AUTOR, LIVRO.EDITORA, LIVRO.DATAPUBLICACAO
FROM LIVRO
INNER JOIN FAVORITOS ON LIVRO.ISBN = FAVORITOS.FAV_ISBN
WHERE FAVORITOS.FAV_CPF = '14876351090';



-- Consulta 2: obter a classificação média e o número de classificações de um livro específico

SELECT LIVRO.ISBN, LIVRO.TITULO, AVG(AVALIACAO.NOTA) AS MEDIA_AVALIACAO, COUNT(AVALIACAO.NOTA) AS NUMERO_AVALIACOES
FROM LIVRO
LEFT JOIN AVALIACAO ON LIVRO.ISBN = AVALIACAO.AVA_ISBN
WHERE LIVRO.ISBN = '9788575413425'
GROUP BY LIVRO.ISBN, LIVRO.TITULO;



-- Consulta 3: Obter os livros que foram emprestados para um usuário específico

SELECT LIVRO.ISBN, LIVRO.TITULO, LIVRO.AUTOR, LIVRO.EDITORA, LIVRO.DATAPUBLICACAO
FROM LIVRO
INNER JOIN EMPRESTIMO ON LIVRO.ISBN = EMPRESTIMO.EMP_ISBN
WHERE EMPRESTIMO.EMP_CPF = '14876351090';



-- Consulta 4: obtenha os usuários que pegaram emprestado um livro específico

SELECT USUARIO.CPF, USUARIO.NOME, USUARIO.SOBRENOME, USUARIO.EMAIL, USUARIO.TELEFONE
FROM USUARIO
INNER JOIN EMPRESTIMO ON USUARIO.CPF = EMPRESTIMO.EMP_CPF
WHERE EMPRESTIMO.EMP_ISBN = '4248985322182';



-- Consulta 5: Obtenha os livros favoritos de um usuário específico, incluindo sua classificação média (se disponível)

SELECT LIVRO.ISBN, LIVRO.TITULO, LIVRO.AUTOR, LIVRO.EDITORA, LIVRO.DATAPUBLICACAO, AVALIACAO.AVERAGE_RATING
FROM LIVRO
INNER JOIN FAVORITOS ON LIVRO.ISBN = FAVORITOS.FAV_ISBN
LEFT JOIN (
    SELECT AVA_ISBN, AVG(NOTA) AS AVERAGE_RATING
    FROM AVALIACAO
    GROUP BY AVA_ISBN
) AS AVALIACAO ON LIVRO.ISBN = AVALIACAO.AVA_ISBN
WHERE FAVORITOS.FAV_CPF = '14876351090';



-- Visão 1: cria uma visão que combina o livro e as informações do usuário para livros emprestados

CREATE VIEW BORROWED_BOOKS_VIEW AS
SELECT LIVRO.ISBN, LIVRO.TITULO, LIVRO.AUTOR, LIVRO.EDITORA, LIVRO.DATAPUBLICACAO, EMPRESTIMO.DATA_EMPRESTIMO, USUARIO.CPF, USUARIO.NOME, USUARIO.SOBRENOME, USUARIO.EMAIL, USUARIO.TELEFONE
FROM LIVRO
INNER JOIN EMPRESTIMO ON LIVRO.ISBN = EMPRESTIMO.EMP_ISBN
INNER JOIN USUARIO ON EMPRESTIMO.EMP_CPF = USUARIO.CPF;