CREATE DATABASE BIBLIOTECA;

USE BIBLIOTECA;

CREATE TABLE LIVRO (
   ISBN VARCHAR(15),
   TITULO VARCHAR(64),
   AUTOR VARCHAR(64),
   EDITORA VARCHAR(64),
   DATAPUBLICACAO DATE,

   PRIMARY KEY (ISBN)
);

CREATE TABLE USUARIO (
   CPF VARCHAR(11),
   NOME VARCHAR(32),
   SOBRENOME VARCHAR(64),
   EMAIL VARCHAR(64),
   TELEFONE VARCHAR(14),
   SENHA VARCHAR(64),
	
   PRIMARY KEY (CPF)
);

CREATE TABLE FAVORITOS (
   FAV_CPF VARCHAR,
   FAV_ISBN VARCHAR,	

   FOREIGN KEY (FAV_CPF) REFERENCES USUARIO (CPF),
   FOREIGN KEY (FAV_ISBN) REFERENCES LIVRO (ISBN)
);

CREATE TABLE AVALIACAO (
   AVA_CPF VARCHAR,
   AVA_ISBN VARCHAR,
   NOTA INT,
   COMENTARIO VARCHAR(128), 	

   FOREIGN KEY (AVA_CPF) REFERENCES USUARIO (CPF),
   FOREIGN KEY (AVA_ISBN) REFERENCES LIVRO (ISBN)
);

CREATE TABLE EMPRESTIMO (
   EMP_CPF VARCHAR,
   EMP_ISBN VARCHAR,
   DATA_EMPRESTIMO DATE,

   	
   FOREIGN KEY (EMP_CPF) REFERENCES USUARIO (CPF),
   FOREIGN KEY (EMP_ISBN) REFERENCES LIVRO (ISBN)
);

CREATE TABLE historico_emprestimo(
   operacao VARCHAR,
   usuario VARCHAR,
   data_operacao DATE
);

